### ISSUE TITLE
segway what is this?

### ISSUE THREAD

**Issue by sergiomarotco** [cider-security-research/top-10-cicd-security-risks#7]
Can you replace the given word "segway" in [SEC-2](https://github.com/cider-security-research/top-10-cicd-security-risks/blob/main/Risks/CICD-SEC-02-Inadequate-Identity-And-Access-Management.md) with a simpler word or phrase, especially for non-English speaking users?
I don't understand the meaning of the word even in the context of the sentence

**Comment by omer-cider** [comment]
Hi @sergiomarotco, that was a typo. Fixed now. Thanks!
